- name: Deploy Pypi
  # You may pin to the exact commit or the version.
  # uses: remorses/pypi@c5a97a333f4d4d59cea6ec2e6a17c15e3241be29
  uses: remorses/pypi@v3
  with:
    # setup file
    setup_file: # optional, default is ./setup.py
    # username
    username: 
    # password
    password: 
